{% set name = "kwcoco" %}
{% set version = "0.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kwcoco-{{ version }}.tar.gz
  sha256: f2b3e40c4e1a230c22960a3d85a94cb685fd4f87858a5174e3d9bac265a53e26

build:
  noarch: python
  entry_points:
    - kwcoco = kwcoco.cli.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=41.0.1
  run:
    - delayed_image
    - jsonschema >=3.2.0
    - kwarray
    - kwimage
    - networkx >=2.7
    - numpy >=1.19.3
    - packaging >=21.3
    - pandas >=1.4.0
    - parse >=1.14.0
    - psutil >=5.6.3
    - python >=3.8
    - rich
    - safer >=4.4.1
    - scikit-learn >=1.0.2
    - scipy >=1.8.0
    - scriptconfig
    - setuptools >=41.0.1
    - sortedcontainers >=2.3.0
    - ubelt >=1.3.6
    - uritools >=3.0.0
    - xarray >=0.16.0

test:
  imports:
    - examples
    - kwcoco
  commands:
    - pip check
    - kwcoco --help
  requires:
    - pip

about:
  home: https://gitlab.kitware.com/computer-vision/kwcoco
  summary: The kwcoco module and cli for image datasets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Erotemic
    - vicentebolea
